name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt install g++ make cmake
      - name: Build
        run: |
          for target in `find * -mindepth 0 -maxdepth 0 -regex "^[0-9]+.*" -type d`; do
            pushd $target
            cmake -S . -B build
            cmake --build build
            popd
          done

